// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: api/hbms.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BookingServices_CreateBooking_FullMethodName = "/api.BookingServices/CreateBooking"
)

// BookingServicesClient is the client API for BookingServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookingServicesClient interface {
	CreateBooking(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*Booking, error)
}

type bookingServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingServicesClient(cc grpc.ClientConnInterface) BookingServicesClient {
	return &bookingServicesClient{cc}
}

func (c *bookingServicesClient) CreateBooking(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*Booking, error) {
	out := new(Booking)
	err := c.cc.Invoke(ctx, BookingServices_CreateBooking_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingServicesServer is the server API for BookingServices service.
// All implementations must embed UnimplementedBookingServicesServer
// for forward compatibility
type BookingServicesServer interface {
	CreateBooking(context.Context, *BookingRequest) (*Booking, error)
	mustEmbedUnimplementedBookingServicesServer()
}

// UnimplementedBookingServicesServer must be embedded to have forward compatible implementations.
type UnimplementedBookingServicesServer struct {
}

func (UnimplementedBookingServicesServer) CreateBooking(context.Context, *BookingRequest) (*Booking, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBooking not implemented")
}
func (UnimplementedBookingServicesServer) mustEmbedUnimplementedBookingServicesServer() {}

// UnsafeBookingServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingServicesServer will
// result in compilation errors.
type UnsafeBookingServicesServer interface {
	mustEmbedUnimplementedBookingServicesServer()
}

func RegisterBookingServicesServer(s grpc.ServiceRegistrar, srv BookingServicesServer) {
	s.RegisterService(&BookingServices_ServiceDesc, srv)
}

func _BookingServices_CreateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServicesServer).CreateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingServices_CreateBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServicesServer).CreateBooking(ctx, req.(*BookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookingServices_ServiceDesc is the grpc.ServiceDesc for BookingServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookingServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.BookingServices",
	HandlerType: (*BookingServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBooking",
			Handler:    _BookingServices_CreateBooking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/hbms.proto",
}
